task5
DavydaVladyslav/csad2425ki404davyda05 pull request #10
Opened 2024-11-23 18:30 UTC by DavydaVladyslav

2024-11-24 19:11 UTC, PavloFedakNULP commented
Please add screen with % of coverage by tests

2024-11-24 19:52 UTC, DavydaVladyslav commented
![coverage](https://github.com/user-attachments/assets/c7a9640b-26b6-4e1f-bf45-6e837139a734)
![test](https://github.com/user-attachments/assets/70c19379-4bca-4296-a242-127a5d69aea2)

2024-11-25 07:54 UTC, PavloFedakNULP requested changes
Coverage must be more than 80%

2024-11-25 08:26 UTC, DavydaVladyslav commented
Виправив

![client_coverage](https://github.com/user-attachments/assets/fafead65-df23-4d24-affc-c3e7f43e5c7a)
![server_coverage](https://github.com/user-attachments/assets/4437363f-2921-498a-b4da-f1c8f2d75c0f)

2024-11-25 09:13 UTC, PavloFedakNULP commented
Коміту з виправленням немає, тільки скрін, закомітьте зміни

2024-11-25 21:06 UTC, PavloFedakNULP approved these changes

2024-11-25 21:26 UTC, merged